---
- name: Подготовка сервера, установка Docker и деплой кода
  hosts: all
  become: true

  vars:
      repo_url: "https://github.com/BalabanovA898/QA_labs"
      dest_dir: "/opt/app"
      repo_branch: "master"

  tasks:
      - name: Создаем папку под проект с правильными правами
        ansible.builtin.file:
            path: "{{ dest_dir }}"
            state: directory
            mode: "0755"

      - name: Копируем docker-compose.yml из раннера на VPS
        ansible.builtin.copy:
            src: "../docker-compose.yml"
            dest: "{{ dest_dir }}/docker-compose.yml"
            mode: "0644"

      - name: Стягиваем свежие образы из Docker Hub и перезапускаем контейнеры
        ansible.builtin.shell: |
            docker compose pull
            docker compose up -d
        args:
            chdir: "{{ dest_dir }}"
